### ISSUE TITLE
Skyroot axes don't double log drops; skyroot swords don't double mob drops

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#12]
Only tested on logs and sheep. Intended behavior: a mob can drop 0 items but never 1, only even numbers, because the drops are always multiplied by 2. 
Logs simply drop one of themselves. skyroot pickaxes and shovels behave as expected.

**Comment by sunsetbear** [comment]
Quick update- skyroot shovels do not duplicate quicksoil.

**Comment by matthewperiut** [comment]
the aether tools should double everything that is an aether mob and aether block that is mineable by the tool? I don't think the original v1.02 b1.7.3 Aether went beyond that?

**Comment by sunsetbear** [comment]
> the aether tools should double everything that is an aether mob and aether block that is mineable by the tool? I don't think the original v1.02 b1.7.3 Aether went beyond that?

Correct, that's the issue I'm reporting. Axes and swords don't do that
