### ISSUE TITLE
The sun spirit has a seizure when attempting to look at the player

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#16]
intended behavior: once the player right clicks the sun spirit, he will acknowledge them by looking at them until they either leave or the fight begins. 

actual behavior: once the player right clicks the sun spirit, he alternates between looking at them and not looking at them every tick for about 2 seconds and then stops trying altogether

**Comment by matthewperiut** [comment]
were you in creative mode? I believe that's why that would have occured, but if not reopen the issue. It may also be because of the chest being in the middle of the room. for now I'm going to close this.
