### ISSUE TITLE
Having any aether armor on, including gloves, nullifies all damage from most sources

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#18]
As described. Gloves are intended to increase damage dealt by the player, not reduce damage, for clarity.

**Comment by matthewperiut** [comment]
Aether armor nullifying damage is actually a stationapi bug, see https://github.com/ModificationStation/StationAPI/issues/83

**Comment by matthewperiut** [comment]
gloves definitely need to have their functionality revised and fixed though!
