### ISSUE TITLE
Skyroot logs often spawn inside leaves

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#22]
When cutting down trees, skyroot logs' dropped items appear inside the surrounding leaves. This makes them a struggle to obtain at times. This is not consistent with vanilla tree behavior or gilded games' Aether's trees' behavior. Also it's a mild inconvenience

**Comment by matthewperiut** [comment]
I got it so that it occurs significantly less frequently, and improved general handling of skyroot axe and getting golden amber.  Thanks for the bug report as always!
