### ISSUE TITLE
Agility cape has no function

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#3]
agility cape's blockstep ability is not happening for me

**Comment by matthewperiut** [comment]
Forgot to add lol I'll fix soon

**Comment by sunsetbear** [comment]
IMPORTANT: appears to be a conflict with unitweaks' "step assist" option. If the option is off, no blockstep, if the option is on, yes blockstep. Overrides the presence of an agility cape. Uninstalling unitweaks fixed the issue. Forgive me for thinking the equivalent of betatweaks wouldn't add blockstep lmfao
