### ISSUE TITLE
Slider dungeon can generate above-ground

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#5]
![image](https://github.com/matthewperiut/aether-fabric-b1.7.3/assets/8252642/5c89d0b5-1d85-41c2-a302-069be8d47a90)

**Comment by matthewperiut** [comment]
That's expected behavior same as the original b1.7.3 aether lol, what exactly would you prefer?

**Comment by sunsetbear** [comment]
I have been playing aether b1.7 rigorously for like a month and not seen this huh

**Comment by matthewperiut** [comment]
Yeah I haven't seen it either, it's very uncommon but the world gen code is 1:1 the same seed produces the same things (in theory)

**Comment by sunsetbear** [comment]
I will cross reference the seed

**Comment by matthewperiut** [comment]
turns out the dungeon gen isnt based on seed GG

**Comment by matthewperiut** [comment]
I genuinely believe its rare enough that I don't want to fix it really, and its pretty hard to fix, so I'm going to not fix it for now unless it occurs often enough, then i'll remaster the slider dungeon if so.
