### ISSUE TITLE
Dungeon trap blocks are sometimes unable to summon their intended mob

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#9]
This makes gathering medals for the valkyrie queen tedious, to say the least. Video: [https://streamable.com/y8bezn](https://streamable.com/y8bezn)

**Comment by matthewperiut** [comment]
I'm pretty confident that's a LockedDungeonStone and not a Trap Block. I'm going to make it so that on boss's death all locked blocks become unlocked and after stepping on a trap it becomes a regular block.

**Comment by matthewperiut** [comment]
gg lol actually already how it works
